### ISSUE TITLE
external.html.twig is not defined.

### ISSUE THREAD

**Issue by SirFiChi** [getgrav/grav-theme-twenty#12]
I tried to embed a mailtrain formular end tried external.
But I get an error:

```
 RuntimeException (400)
Template "external.html.twig" is not defined.
Previous exceptions

    Template "external.html.twig" is not defined. (0)

```

**Comment by rhukster** [comment]
This has been addressed in Grav 1.7 by including an empty `templates/external.html.twig` in Grav core.  A quick fix for you is to include an empty file called `external.html.twig` in the theme's `templates/` folder.
