### ISSUE TITLE
Hardcoded Navigation

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav-theme-twenty#2]
Navigation should be controlled by the Page structure.  Currently it's hardcoded in the theme.  This needs to be addressed.

e.g. https://github.com/getgrav/grav-theme-twenty/blob/develop/templates/partials/header.html.twig#L7

**Comment by siren386** [comment]
I want to add the info, that, if there are more than 5 menu-options added to the header.html.twig, it shows a ugly scrollbar on mobile-phones.

![scroll](https://cloud.githubusercontent.com/assets/14054474/10529307/0b80ac66-739d-11e5-8410-735ad7618a16.JPG)

**Comment by hexplor** [comment]
I noticed Twenty received massive update from HTML5UP including removal of stupdi "noscript" tags. Expect some updates including automatic menu handling as well.
