### ISSUE TITLE
Menu bar not rendering correctly

### ISSUE THREAD

**Issue by NeuroWinter** [getgrav/grav-theme-twenty#6]
Hello, I just installed the theme and out of the box it doesnt look right:

![image](https://user-images.githubusercontent.com/7663857/27620950-66dd66a8-5c21-11e7-85fb-81127660cbaa.png)

How would I resolve this?

**Comment by rhukster** [comment]
The theme is just a theme. What you need is the Twenty skeleton. That is grav, theme, plugins, content and configuration all in one zip.
